name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_target:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      python-version:
        description: Desired python version
        required: false
        default: 3.12

env:
  PYTHON_VERSION: ${{ inputs.python-version || '3.12' }}

jobs:
  setup:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}

  build-example:
    runs-on:
      - ubuntu-latest
    needs: [setup]
    steps:
      - name: Build example
        uses: ./.github/actions/build
        with:
          working-directory: example

  build-linear-algebra:
    runs-on:
      - ubuntu-latest
    needs: [setup]
    steps:
      - name: Build example
        uses: ./.github/actions/build
        with:
          working-directory: linear_algebra
