name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_target:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      python-version:
        description: Desired python version
        required: false
        default: 3.12
    is-continue-on-lint-error:
      description: If true then build will continue despite of presence of linting error
      required: false
      default: "true"

env:
  PYTHON_VERSION: ${{ inputs.python-version || '3.12' }}
  IS_CONTINUE_ON_LINT_ERROR: ${{ inputs.is-continue-on-lint-error || 'true' }}

jobs:
  build-example:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build example
        uses: ./.github/actions/build
        with:
          working-directory: example
          artifact-name: example
          is-continue-on-lint-error: ${{ env.IS_CONTINUE_ON_LINT_ERROR }}

  build-linear-algebra:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build linear algebra
        uses: ./.github/actions/build
        with:
          working-directory: linear_algebra
          artifact-name: linear_algebra
          is-continue-on-lint-error: ${{ env.IS_CONTINUE_ON_LINT_ERROR }}
